Valleo/Models/Matrix.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Valleo.Models
{
    public class Matrix
    {
        public int ID { get; set; }
        [Range(3, 5)]
        public int orderMatrix { get; set; }
 
    }

}

Valleo/Controllers/MatrixController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Valleo.Controllers
{
    public class MatrixController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Game()
        {

            return View();
        }
    }
}

Valleo/Views/Matrix/Game.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Swapping Songs</title>
</head>
<body>
    <button >1</button><button>2</button><button>3</button>
    <br />
    <button>4</button><button>5</button><button>6</button>
    <br />
    <button>7</button><button>8</button><button>9</button>
    <br />

    <div id="loginBlock">
        Введите логин:<br />
        <input id="userName" type="text" />
        <input id="loginBtn" type="button" value="Войти" />
    </div><br />

    <div id="header"></div><br />

    <div id="inputForm">
        <input type="text" id="message" />
        <input type="button" id="sendBtn" value="Отправить" />
    </div>
    <div id="chatroom"></div>

    <!--подключаем скрипт-->
    <script src="js/signalr-client-1.0.0-alpha2-final.min.js"></script>

    <script>
        let url = window.location.href.toString();
        let hubUrl = url + 'chat';
        let httpConnection = new signalR.HttpConnection(hubUrl);
        let hubConnection = new signalR.HubConnection(httpConnection);
        let userName = '';

        hubConnection.on("Send", function (message, userName) {

            // создаем элемент <b> для имени пользователя
            let userNameElem = document.createElement("b");
            userNameElem.appendChild(document.createTextNode(userName + ': '));

            // создает элемент <p> для сообщения пользователя
            let elem = document.createElement("p");
            elem.appendChild(userNameElem);
            elem.appendChild(document.createTextNode(message));

            var firstElem = document.getElementById("chatroom").firstChild;
            document.getElementById("chatroom").insertBefore(elem, firstElem);

        });

        // установка имени пользователя
        document.getElementById("loginBtn").addEventListener("click", function (e) {
            userName = document.getElementById("userName").value;
            document.getElementById("header").innerHTML = '<h3>Welcome ' + userName + '</h3>';
        });

        document.getElementById("sendBtn").addEventListener("click", function (e) {
            let message = document.getElementById("message").value;

            hubConnection.invoke("Send", message, userName);
        });

        hubConnection.start();
    </script>

</body>
</html>

Valleo/Views/Matrix/Index.cshtml
<h1>Задайте размер поля игры от 3 до 5</h1>

<input id="Order" type="text" />
<br />
<li><a asp-area="" asp-controller="Matrix" asp-action="Game">Начать игру</a></li>